---
title:  'In hoeverre zijn Popkoren in Nederland echt koren die Popmuziek zingen?'
author: 'Rolinde Zieverink'
date:   '2020'
output: 
    flexdashboard::flex_dashboard:
        storyboard: true
        theme: flatly
---

```{r setup}
# In order to use these packages, we need to install flexdashboard, plotly, and Cairo.
library(tidyverse)
library(plotly)
library(spotifyr)
source('spotify.R')
```

### Popkoren in Nederland 

In Nederland kennen wij een grote hoeveelheid aan mensen die zingen. Volgens het *Sociaal en Cultureel Persberau* zingen 25% van de Nederlanders met enige regelmaat. Er is een grote amateursector met koren. Hiervan zijn steeds meer koren die zich zelf popkoren noemen. Ik vraag mij echter af in hoeverre deze koren ook écht popkoren zijn. 

Om dit te kunnen beantwoorden heb ik 9 verschillende koren uit heel Nederland genomen en hun repertoire geanaliseerd. Verder heb ik de Top100 uit Nederland genomen die elk jaar verschijnt. Ik denk dat de Top 100 in Nederland een goede weergave is van wat popmuziek is omdat deze lijst samen wordt gesteld door de meeste legale downloads en singles die worden verkocht. Ook worden de cijfers van muziekstreamingsdiensten meegeteld. Al bij al kom je dan bij de Top100 lijst, dus de meeste populaire muziek vanuit het oogpunt van Nederlanders. 


Hieronder volgen de Spotify features uitgelegd

Alle_koren %>%
  ggplot(aes(x = playlist, y = energy)) +
  geom_boxplot() + xlab("Koren") + ylab("Energy")

Alle_koren %>%
  ggplot(aes(x = playlist, y = danceability)) +
  geom_boxplot() + xlab("Koren") + ylab("Danceability")

Alle_koren %>%
  ggplot(aes(x = playlist, y = valence)) +
  geom_boxplot() + xlab("Koren") + ylab("Valence")

Alle_koren %>%
  ggplot(aes(x = playlist, y = liveness)) +
  geom_boxplot() + xlab("Koren") + ylab("Liveness")

Alle_koren %>%
  ggplot(aes(x = playlist, y = acousticness)) +
  geom_boxplot() + xlab("Koren") + ylab("Acousticness")

Alle_koren %>%
  ggplot(aes(x = playlist, y = speechiness)) +
  geom_boxplot() + xlab("Koren") + ylab("Speechiness")



Dus b.v.:


energy <- ggplot(aes(x = playlist, y = energy)) +
  geom_boxplot() + xlab("Koren") + ylab("Energy")

ggplotly(energy)



_________ 

I want to know whether choirs who name themselves popchoirs are really popchoirs, that is, whether their repertoire mainly consists of songs in the genre pop. I will choose 10 different choirs and will analyse their repertoire. These can be found on their websites.

First, I chose the following 10 choirs:

1. Firma Vocaal, Weesp
2. Popolo, Nijmegen
3. Popkoor Koffer, Utrecht
4. Popkoor Prestige, Amsterdam
5. Popkoor Noisey Voices, Amsterdam
6. Popkoor Remix, Almere
7. Popkoor Amazing, Nieuwegein
8. Studentenpopkoor Plica Vocalis – Pop, Nijmegen
9. Hartkoor, Utrecht
10. Popkoor Akkoord, Roosendaal
11. Eurokoor, Leiden
12. Vocal Essen, Oldenzaal

Second, I made playlists for all the above mentioned choirs.

Third, I will compare each of these playlists with a playlist I make on my own -> Popmusic in Holland from 1965-2020.

Before I can compare the playlists which each other I need a definition of what popmusic in Holland is.

What I need to do for now/this week; https://www.top40.nl/bijzondere-lijsten/top-100-jaaroverzichten/1965 This website lists the 100 most popular songs in Holland of each year since 1965. Since 55 years with 100 songs is rather a lot of work I will focus on the first 40 songs of each year. This will be a total amount of songs of 2200. From here I can make the make the definition of what we could call in Holland popular music. After that I can start comparing all the popchoir playlists with the playlist I made for 'defining pop'


***

This is a second column of introductory text.


### Nederlandse popmuziek door middel van de Top100

To define what could be called popmusic in Holland I took 55 playlists from the Top100 in Holland from 1965-2020. Each playlist consists approximately 100 songs from that specific year. With rbind() I combined all the songs together. I removed the songs that were doubled in the playlists. So from 55 years the Top 100 songs the data is 5044 songs. This means I have 5044 songs to define Popmusic. 

To specify more the components we will discuss the characteristics of popmusic with the features of spotify: 
  
  1. Energy
  2. Mode
  3. Key
  4. Danceability
  5. speechiness
  6. acousticness
  7. loudness
  8. instrumentallness
  9. liveness
  10. valence
  11. tempo
  12. time-signature
  13. 


***

Hier tabellen van de gemiddelde van alles -> een tabel of meerdere? 

```r
plot(x = playlistYears, y = playlistAveragesEnergyList, type="l", col="blue",ylim = c(0,1), xlab = "Jaartal", ylab = "Waarde")
lines(x = playlistYears, y = playlistAveragesDanceabilityList, type="l", col="pink")
lines(x = playlistYears, y = playlistAveragesSpeechinessList, type="l", col="green")
lines(x = playlistYears, y = playlistAveragesAcousticnessList, type="l", col="red")
lines(x = playlistYears, y = playlistAveragesLivenessList, type="l", col="purple")
lines(x = playlistYears, y = playlistAveragesValenceList, type="l", col="black")
legend(1965, 1.02, legend=c("Energy", "Danceability","Speechiness", "Acousticness", "Liveness", "Valence"),
       col=c("blue", "pink", "green", "red", "purple", "black"), lty=1, cex=0.70)
# ggplotly(plot)
plot
```


### Chosen popchoirs

Hier de popkoren die ik ga vergelijken 

uitproberen of de tabel van Ahsley wel werkt.



